### ISSUE TITLE
Trouble performing commit

### ISSUE THREAD

**Issue by crabinak** [agritheory/stonecrop#111]
@agritheory @Alchez I have been having some trouble performing commits since earlier today. Is anyone else having this issue (files remain staged and I'm getting a 127 error that seems to be blocking commits). Have either of you experienced this? I tried a fresh clone of the repo elsewhere and ran into the same issue.

**Comment by agritheory** [comment]
@crabinak I have not, I was able to make some trivial changes, commit to a branch and push it up. Sounds like we should look at it together.

**Comment by crabinak** [comment]
@agritheory I got it figured out. There was a corrupt pre-commit file in .git that was causing it.
