### ISSUE TITLE
[themes][aform] ATable headers seems heavy compared to AForm field labels 

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#118]
As far as communicating importance to the user, the field level label and column label are equivalent, but they sure do not feel that way. I suspect the the field label needs to be "heavier" (maybe in font weight, maybe in "impact") and the table column header styles are by comparison too dark and heavy. 

![image](https://github.com/agritheory/stonecrop/assets/18033666/88b7d39f-54f9-42cd-a4b8-350dcb63bac4)

![image](https://github.com/agritheory/stonecrop/assets/18033666/d2143b70-519a-406f-9bd1-e5c80d2e3971)

Another thought about stylistic consistency: I feel like the distance between the top and bottom of the field label border should be the same as the default line height in the table.

**Comment by agritheory** [comment]
@crabinak Interested to hear your thoughts on this one and any adjacent issues you notice.

**Comment by crabinak** [comment]
@agritheory I'll take a look. I agree on field padding. The field labels can probably bump up out of the box and get a bolder treatment. I'll experiment and see what works.
