### ISSUE TITLE
[utilities] VueUse upgrade limitation

### ISSUE THREAD

**Issue by Alchez** [agritheory/stonecrop#120]
VueUse released [v10](https://github.com/vueuse/vueuse/releases/tag/v10.0.0) last year, but we have a breaking change with [`useElementVisibility`](https://vueuse.org/core/useElementVisibility/#useelementvisibility) while working with keyboard navigation. In versions <10, they were using a scroll event handler, but they updated the internals of the composable to use [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) instead. This is causing our keyboard navigation that relies on the composable to stop working.

Until we figure out a way to use the new APIs, we're blocked from upgrading to v10 if ever it's required.

**Comment by agritheory** [comment]
What is degree of difficulty with vendoring the v10 version of the composable into /utilities?

**Comment by Alchez** [comment]
@agritheory do you mean moving the current working version of the composable into Stonecrop?

If so, then that should be doable since VueUse is open-source. We can just package it ourselves and upgrade vueuse across the project to v10.

**Comment by agritheory** [comment]
Yes, we should attribute it and a comment on the background. I think it's also worth raising an issue in the VueUse repo about migration between the versions and if they have a suggestion about switch it with a scroll sensitive one. It could still be available but in a differently-named composable.

**Comment by Alchez** [comment]
@agritheory Makes sense. Although I'm gonna try and implement the new version and see if that works (only because I have a feeling this is not an issue in the composable and could be related to my code).

If it takes too long or it doesn't seem possible, I'll bring in the v9 composable and add an issue on their repo.
