### ISSUE TITLE
[ATable] inject collect and inject variables into ATable

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#139]
```js
                {
                    "component": "WorkQueueDescription",
                    "name": "description",
                    "fieldtype": "Data",
                    "label": "Description",
                    "required": false,
                    "width": "50ch",
                    "format": "(cell) => {console.log(cell)}"
                    "format": "(row, cell) => {console.log(row, cell)}"
                    "format": "(table, row, cell) => {console.log(table, row, cell)}"
                },
```

This will allow formatting or masking of any of these variables. I think this API is OK to be inferred based on the number of arguments provided.

**Comment by Alchez** [comment]
@agritheory I don't think a JSON object allows duplicate keys. Is the idea here to do conditional formatting? If yes, maybe we can try doing something like the following to allow arbitrary inputs:

```jsonc
{
    "component": "WorkQueueDescription",
    "name": "description",
    "fieldtype": "Data",
    "label": "Description",
    "required": false,
    "width": "50ch",
    "format": "({ table, row, cell }) => {console.log(table, row, cell)}"
},
```

We already allow the following too:

```jsonc
{
    "format": "(obj) => {console.log(obj.table, obj.row, obj.cell)}"
}
```

**Comment by agritheory** [comment]
@Alchez Yes, I wanted to format a link in the Work Queue context, let me try this. 

I am getting: `undefined undefined undefined`

**Comment by agritheory** [comment]
@Alchez I think this may have broken, `"format": "() => return <a href=''>Link</a>"` does not display anything.

**Comment by Alchez** [comment]
> @Alchez Yes, I wanted to format a link in the Work Queue context, let me try this.
> 
> I am getting: `undefined undefined undefined`

@agritheory Oh, I misunderstood what you meant completely. Currently, we do only pass in the cell value, but I can make a PR against this issue that'll also pass in the other variables. I'm wondering if we should just pass the table data-store? That should allow anyone to abritrary read values in real-time.

> @Alchez I think this may have broken, `"format": "() => return <a href=''>Link</a>"` does not display anything.

I think the syntax might be incorrect here. You only need `return` if you're using the `() => return {}` function format. Additionally, I think you'll have to wrap the hyperlink text around quotes as well.

**Comment by agritheory** [comment]
@Alchez Can you pick this up? We need it for the Work Queue UI.

**Comment by agritheory** [comment]
@Alchez This is what I tried in Autoreader context:

```json
                {
                    "component": "ATextInput",
                    "name": "reference_type",
                    "fieldtype": "Data",
                    "label": "Document",
                    "required": false,
                    "read_only": true,
                    "width": "10ch",
                    "format": "({ table, row, cell }) => `<a href=\"/app/${row.reference_type}/${row.reference_name}\">${row.reference_name}</a>`"
                }

```

**Comment by Alchez** [comment]
@agritheory did it work or fail somewhere?

**Comment by Alchez** [comment]
@agritheory I think I know what's going wrong here. There's actually two variables that the format function receives:

- `value`, which corresponds to the raw cell value provided by the server
- `context`, which for ATable is an object that contains information on the table, row and cell as well.

Can you try doing the following:

```
"format": "(value, { table, row, cell }) => `<a=href=\"/app/${row.reference_type}/${row.reference_name}\">${row.reference_name}</a>`"
```
