### ISSUE TITLE
[beam] Metadata/ Document component

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#145]
![image](https://github.com/user-attachments/assets/ebef69d7-1837-4925-ad7d-ead0568bc93e)

Let's assume these items are required in a single document. We need to know what kind of document it is (header) and three or four configurable facts about it. Examples given in context on the BEAM repo.

**Comment by crabinak** [comment]
@agritheory Can you send me a few screenshots highlighting the relevant information we would want to include here?

**Comment by agritheory** [comment]
@crabinak I updated this with a very poor idea of what I mean. Don't worry about the property names, we can switch that around as needed

**Comment by crabinak** [comment]
@agritheory Let me know if this is heading in the right direction. I have job cards that list the quantity with actions for shipping, receiving, components required and the status of the job. 
![beam-metadata-doc_01](https://github.com/user-attachments/assets/2f34c0d4-888c-4534-bb18-3d5ca2819e2e)

**Comment by agritheory** [comment]
@crabinak This looks great. There's some nomenclature we'll change on the way to ERPNext, but yes, this is where we want to be going.
I think the "components" section you have there should scroll separately or put another way, this metadata component should stick to the top.

**Comment by crabinak** [comment]
@agritheory Here is an option where the components are scrollable. 
![beam-metadata-doc_02](https://github.com/user-attachments/assets/18a16ed9-4f25-40c3-a74d-40a5016d3820)

**Comment by agritheory** [comment]
@crabinak Awesome, let's get it in a PR.

**Comment by agritheory** [comment]
@crabinak What's the status on this?

**Comment by crabinak** [comment]
@agritheory I just created a PR adding the design file into stonecrop/beam/design.

**Comment by agritheory** [comment]
@crabinak Design spec merged, let's turn this into a component with a slot.
