### ISSUE TITLE
[beam] Make Navbar compatible with Vue Router <RouterLink> component 

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#154]
```html
<template #navbaraction><RouterLink route="#/home">HOME</RouterLink></template>
```

**Comment by Alchez** [comment]
@agritheory I'm not exactly sure what is required for this one. The `navbaraction` slot already allows RouterLink in [implementations](https://github.com/agritheory/beam/pull/121/files#diff-7b2d8db89c023e9ea4be80ad459ebe23d59257ce331877660b745064075732ae).
