### ISSUE TITLE
[utilities] applying event listeners to a limited set of selectors

### ISSUE THREAD

**Issue by Alchez** [agritheory/stonecrop#16]
**Problem:** Applying event listeners to a limited set of selectors (e.g. all cells in a table except the number column) in the context of keyboard navigation

**Context:** If a user provides a string as the selector input to the composable, we currently run `document.querySelectorAll` to fetch all matching nodes, which returns ALL nodes on that page, which may or may not be implicit.

**Possible Solution(s):**
- We keep the status quo.
  - **Pro:** The user has the responsibility to explicitly state what selectors they would like to apply the listeners on.
  - **Con:** This limits the use of the composable, since the user has to do more to have control over the set of selectors they want. This is fairly subjective, since JS can allow fine control in `querySelectorAll`.
- We accept a parent element and apply the `querySelectorAll` call on that instead
  - **Pro:** The user can easily manage scopes for the target elements, and re-use across different listener options.
  - **Con:** If this option is provided, we'll need to add a default to it. `document` sounds fairly reasonable. This can be made easier with API documentation.

**Additional Info:** Either way, we will also probably need to expand on the types of inputs that the `useKeyboardNav` composable should receive.

**Comment by agritheory** [comment]
I don't think this is an either/or scenario. Given that a parent element is required:
- [x] When provided only a parent component, the composable should traverse all [_visible_](https://github.com/agritheory/stonecrop/issues/15) elements with a > -1 tabIndex
- [x] When a parent element and a selector is provided, the selector returns matching values inside the parent element. This allows the user to skip an index or non-editable total column, for example. The default of traversing based on default tabIndex is not applied
- [x] When an array of elements is provided, traverse only those elements.

The goal here is a reasonable approach and good developer experience, and I think we're on the right track.
