### ISSUE TITLE
[beam] Toast component

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#164]
I imagine this to be a different component than the BeamModal one, but I could be convinced. 

In order to harmonize with the ActionFooter component, we want these to appear at the top/center of the interface.

**Comment by crabinak** [comment]
@agritheory I'm working on this currently. I've found [this package (vue-toast-notification)](https://www.npmjs.com/package/vue-toast-notification) that saves the trouble of developing a toast component from scratch. I'm seeing if I can customize the styling on it.
