### ISSUE TITLE
[ATable] ATable API(s) for full width

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#48]
We want to be able to tell a table to size its columns to fill the available space. This should be a top-level API to progressively hide columns as horizontal space is reduced (or not) as well as respecting the "width" parameter to mean "min-width".

**Comment by Alchez** [comment]
@agritheory, just thinking out loud here, so I don't know which ones of these are important right now :sweat_smile: 

- Should widths be provided via the schema to control individual table renders (that may be inside forms or fieldsets)? Or should it be on a higher level, when a user renders a table via the API?
- Should there be a default expectation to render tables at full-width, if a width is not provided?
- If we resize a table or window, and columns need to start hiding, should there be a list of columns that take precedence?
  - Alternatively, should the higher priority columns be rendered first, and the auto-hide behaviour doesn't need to care which columns it will hide?
- How many columns should we allow rendering, given a screen size?
  - Alternatively, should there be a min-width to a column? If yes, should it be defined in the schema?
  - We'd also need to set a max-width for the index column, in case the table is rendering numbered rows.

**Comment by agritheory** [comment]
> Should widths be provided via the schema to control individual table renders (that may be inside forms or fieldsets)? Or should it be on a higher level, when a user renders a table via the API?

Ideally both. There are going to be cases of entirely schema-driven use and some where it will be passed in directly. 

> Should there be a default expectation to render tables at full-width, if a width is not provided?

My instinct is the opposite, to use the sum of the columns width values as the default width. This makes more sense when you have some kind of horizontal overflow (column per week of the year scenario).

> If we resize a table or window, and columns need to start hiding, should there be a list of columns that take precedence?
Alternatively, should the higher priority columns be rendered first, and the auto-hide behavior doesn't need to care which columns it will hide?

I think we can implement this, with a two-tier priority algorithm that expects a number and defaults to the columns index if not provided. I think this feature is not likely to be used often but will be critical when it is. It will also help with frozen column requirements, which is something we want to do eventually.

> How many columns should we allow rendering, given a screen size?

No limit, horizontal overflow is OK.

> Alternatively, should there be a min-width to a column? If yes, should it be defined in the schema? 

If the full-width property is checked the `width` key becomes a `min-width` attribute.

> We'd also need to set a max-width for the index column, in case the table is rendering numbered rows.

Sure, sounds good
