### ISSUE TITLE
[ATable] Draggable/ Resizable columns in ATable

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#49]
A header component that can slot into ATable

https://vueuse.org/core/useDraggable/

This should be exposed as configuration / schema API at the ATable level

**Comment by bhattdevarsh** [comment]
Trial conclusion: `useDraggable` is not the solution for this scenario.

**Comment by bhattdevarsh** [comment]
`useDraggable` is possible but will require muti-level logical changes to make sure other element like cell and header are aligned correctly and adapt the drag event. Additionally there is something called `axis` that can be programmed to move element only in preferred direction, but that is available in `v10.9.0` and not on `v9.13.0`.

![image](https://github.com/agritheory/stonecrop/assets/58166671/8efde448-dbc6-42b5-be34-eca09551c37f)

https://github.com/agritheory/stonecrop/assets/58166671/fc3b2968-a161-488e-8424-28a16a84c870

**Comment by Alchez** [comment]
@agritheory @bhattdevarsh This is also related to #120. The PR that I've raised should allow us to start using v10 APIs.

**Comment by Alchez** [comment]
@bhattdevarsh this one can move ahead with v10.9.0

**Comment by bhattdevarsh** [comment]
Closing this as the PR is merged.
