### ISSUE TITLE
Make TS config common

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#56]
Use root level tsconfig and import it anywhere else its needed. Single source of truth

**Comment by Alchez** [comment]
@agritheory, this is already available in the monorepo. Is there anything particular you wanted to pull into the project-specific tsconfig files?

**Comment by agritheory** [comment]
I wanted to make sure they _all_ work this way. Maybe this comes down to documentation. As you know, I'm just getting acquainted with TS.
