### ISSUE TITLE
[AForm][ATable] File Attach Component

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#64]
https://vueuse.org/core/useFileDialog/

Should work in both AForm and ATable

**Comment by bhattdevarsh** [comment]
@Alchez @agritheory 

I am thinking to place the component under the form variant and expandable variant for AForm and ATable respectively, If we think it is better to be represented somewhere else then please let me know.

AForm:
![image](https://github.com/agritheory/stonecrop/assets/58166671/93797c97-2952-47a7-b1ce-f63960654c05)

ATable:
![image](https://github.com/agritheory/stonecrop/assets/58166671/ed733077-1695-4ddf-af2b-838c47f511a9)
