### ISSUE TITLE
[docs] Automatic API discovery 

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#70]
Noting Baklava's nice API documentation: https://newcat.github.io/baklavajs/api/index.html#/@baklavajs%2Fcore
And how it was generated:  https://github.com/newcat/baklavajs/blob/master/docs/apiPlugin.js

For actual documentation I think I would organize the types in a more hierarchical way.

ADR:
Why now, before this package is public?
It will allow us to synchronize APIs across components, utilities and composables, detecting orphans, omissions, and nomenclature problems. Generating this data will allow us to add CI and/or pre-commit checks to make sure we're being consistent or breaking as appropriate.

**Comment by Alchez** [comment]
@agritheory I gave this a quick look, and it seems like Baklava now uses [Vitepress](https://vitepress.dev/) to build their [main static docs site](https://v2.baklava.tech/) and [TypeDoc](https://typedoc.org/) to generate the [API hierarchy](https://v2.baklava.tech/api/).
